import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { NavigationEvents } from "./components/navigation-events"
import ProgressBar from "@badrap/bar-of-progress"
import { Suspense } from "react"
import NextTopLoader from "nextjs-toploader"

const progress = new ProgressBar({
  size: 4,
  color: "#FD5B61",
  className: "z-50",
  delay: 100,
})

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader 
        color="#FD5B61"
        initialPosition={0.08}
        crawlSpeed={200}
        height={5}
        crawl={true}
        showSpinner={true}
        easing="ease"
        speed={200}
        shadow="0 0 10px #2299DD,0 0 5px #FD5B61"
        />

        {children}

        {/* <Suspense fallback={null}>
          <NavigationEvents />
        </Suspense> */}
      </body>
    </html>
  )
}
